title: make-me-happy
hero_image: images/banner.png
description: make-me-happy description
version: 4
listed: false
copyedit: false
last_tested: "2019-06-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
